	select count(1) into V_COUNT from DTVLA.DVM_VALOR_CANONICO where VALOR_CANONICO == {{ VALORES.VALOR_CANONICO }} and ID_ENTIDAD_CANONICA in (select id from DTVLA.DVM_ENTIDAD_CANONICA where NOMBRE = '{{ GET_DATA('DVM_ENTIDAD_CANONICA', 'NOMBRE', VALORES.ID_ENTIDAD_CANONICA) }}');
	if V_COUNT > 0 then
		delete from DTVLA.DVM_VALOR_CANONICO where VALOR_CANONICO = {{ VALORES.VALOR_CANONICO }} and ID_ENTIDAD_CANONICA = {{ VALORES.ID_ENTIDAD_CANONICA }};
	end if;
